import type { TodayBriefPayload } from "@/lib/chief-of-staff/types";
import { getPreviewRestaurant } from "@/lib/preview/ui-preview";

export function getPreviewChiefOfStaffBrief(): TodayBriefPayload {
  const r = getPreviewRestaurant();
  return {
    greeting: `Good morning, ${r.name}.`,
    aiPersonality: "BALANCED",
    generatedAt: new Date().toISOString(),
    summary: {
      revenueHealthLine: "Revenue appears healthy this week.",
      revenueHeadline: "Guests may be slipping away before they book — your audit flagged perception gaps.",
      taskCount: 6,
      totalMinutes: 11,
      revenueOpportunityLow: 320,
      revenueOpportunityHigh: 900,
      needToKnow: ["Father's Day is 14 days away.", "Review score steady at 4.6★."],
      suggestions: [
        "Reply to 5 reviews",
        "Post 3 times this week",
        "Add 10 customer photos",
        "Approve summer campaign",
      ],
      holidayBlock: {
        eventName: "Father's Day",
        daysAway: 14,
        emailPrepared: true,
        instagramPrepared: true,
        bannerPrepared: true,
      },
    },
    tasks: [
      {
        id: "preview-1",
        title: "Reply to 4 Google reviews",
        detail: "Recent guests mentioned great food — a quick reply builds trust.",
        category: "REVIEWS",
        source: "AUDIT",
        status: "PENDING",
        impactLabel: "Reputation",
        estimatedMinutes: 8,
        confidenceScore: 88,
        revenueLowGbp: null,
        revenueHighGbp: null,
        requiresIntegration: null,
        auditId: null,
      },
      {
        id: "preview-2",
        title: "Approve Father's Day campaign",
        detail: "Email, Instagram, and website banner drafts are ready.",
        category: "HOLIDAY",
        source: "AI",
        status: "PENDING",
        impactLabel: "Seasonal revenue",
        estimatedMinutes: 3,
        confidenceScore: 86,
        revenueLowGbp: 320,
        revenueHighGbp: 900,
        requiresIntegration: null,
        auditId: null,
      },
      {
        id: "preview-3",
        title: "Post 3 times this week on social",
        detail: "Top competitors posted 5 times — consistency matters.",
        category: "SOCIAL",
        source: "AI",
        status: "PENDING",
        impactLabel: "+27% reach est.",
        estimatedMinutes: 5,
        confidenceScore: 72,
        revenueLowGbp: null,
        revenueHighGbp: null,
        requiresIntegration: null,
        auditId: null,
      },
      {
        id: "preview-4",
        title: "Respond to Instagram DMs",
        detail: "Quick replies convert enquiries into bookings.",
        category: "SOCIAL",
        source: "AI",
        status: "PENDING",
        impactLabel: "Conversion",
        estimatedMinutes: 4,
        confidenceScore: 68,
        revenueLowGbp: null,
        revenueHighGbp: null,
        requiresIntegration: "Instagram",
        auditId: null,
      },
    ],
  };
}
