-- Expand ServiceRequestType for dashboard service surfaces
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'MENU';
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'LISTINGS';
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'ORDERING';
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'DELIVERY';
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'CATERING';
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'SOCIAL';
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'REVIEWS';
ALTER TYPE "ServiceRequestType" ADD VALUE IF NOT EXISTS 'BRAND_PHOTOS';
