-- Enable Row Level Security on public tables exposed to Supabase PostgREST.
-- KOB uses Prisma (postgres pooler role) for all reads/writes — that bypasses RLS.
-- With RLS on and no permissive policies for anon/authenticated, the Data API cannot leak rows.

ALTER TABLE IF EXISTS public."Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."TeamMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Restaurant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Integration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."GrowthInsight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Recommendation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."GeneratedContent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Campaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Keyword" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."WebsiteEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."DigestRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."DemoRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."DailyScan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Asset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CustomerReview" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ReviewReply" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ReviewerProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AgentAction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."OutboundLead" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."StripeWebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."VisibilityAudit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."SiteScan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public._prisma_migrations ENABLE ROW LEVEL SECURITY;
